%YAML:1.0


#--------------------------------------------图像基本信息-------------------------------------------------------
#图片路径（注意最后无斜杠）
img_path: "./intrinsic_calibrate_data"
#图片类型
img_type: "png"
#--------------------------------------------------------------------------------------------------------------


#------------------------任务信息（去畸变一次：用于求一组内参任务，多次：用于纯去畸变任务）------------------------
#去畸变次数（去畸变一次：1，去畸变多次：5）  
all_undist_time: 1
#迭代次数（去畸变一次：120，去畸变多次：25）
loop_num: 120
#剔除点搜索次数去畸变一次：50，去畸变多次：25）
try_delete_times: 50
#--------------------------------------------------------------------------------------------------------------


#---------------------------------------------检测方法信息------------------------------------------------------
#cctag最小搜索距离（cctag个数小于10时在0-10中调整）
cctag_distSearch: 3
#椭圆拟合最低得分（在0.3-1.0中调整，一般不用调整）
ellipse_min_score: 0.8
#--------------------------------------------------------------------------------------------------------------


#---------------------------------------------标定板信息-------------------------------------------------------
#标定板尺寸(mm)
#A1: [841,594]  A2: [594,420]  A3: [420,297]  A4: [297,210]  A5: [210,148]
board_size: [841,594]
#标定板圆心距离(mm)
#A1: 80  A2: 57  A3: 40  A4: 28  A5: 20
markers_distance: 80
#标定板横向圆心个数
markers_width_num: 10 
#标定版纵向圆心个数
markers_height_num: 7 
#标定板最大的cctag id（从0开始算起）
markers_max_id: 15 
#标定板cctag圆环的数量
markers_rings_num: 3 
#标定板背景颜色，白色:0    黑色:1
markers_background_color: 1 
#--------------------------------------------------------------------------------------------------------------


#---------------------------------------------结果保存信息-------------------------------------------------------
#标定结果保存文件名
parameter_save_path: "./intrinsic_calibrate_data/cam_all_parameter" 
#每次去畸变图存储路径（最后无"/"）
path_undistcoff_img_single: "./intrinsic_calibrate_data/undistcoff_img" 
#圆心检测结果
path_img_result: "./intrinsic_calibrate_data/img_result/" 
#边缘检测结果
path_center_result: "./intrinsic_calibrate_data/center_result/" 
#鸟瞰图转换结果
path_warp_result: "./intrinsic_calibrate_data/warp_result/" 
#--------------------------------------------------------------------------------------------------------------

radius: 50